In [2]:
import numpy as np

## DataTypes and attributes

In [3]:
# main datatype = ndarray (n- dimentional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a1.shape

(3,)

In [7]:
a1.ndim, a2.ndim

(1, 2)

In [8]:
a1.dtype

dtype('int32')

In [9]:
a1.size, a2.size

(3, 6)

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame(a1)

In [12]:
df

0
0  1
1  2
2  3

In [13]:
df2 = pd.DataFrame(a2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

## 2. Creating Arrays

In [14]:
ones = np.ones((2,3))

In [15]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
zeros = np.zeros((2,3))
zeros.dtype

dtype('float64')

In [17]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0,10,4)

In [19]:
range_array

array([0, 4, 8])

In [20]:
random = np.random.randint(0,10,size=(2,4))

In [21]:
random

array([[7, 3, 1, 1],
       [4, 5, 6, 9]])

In [22]:
random2 = np.random.random((2,3))
random2

array([[0.65557656, 0.44474551, 0.65958644],
       [0.74017526, 0.04595395, 0.56973258]])

In [23]:
random3 = np.random.rand(4,3)
random3

array([[9.71882009e-01, 4.36077363e-01, 7.96716983e-01],
       [6.44861500e-01, 5.26797986e-01, 4.17733724e-04],
       [9.88216010e-01, 9.50210325e-01, 6.05541905e-01],
       [9.89277943e-02, 6.91407954e-01, 4.02160358e-01]])

In [24]:
# Pseudo-random numbers
# np.random.seed()


Seed:
Seed is the "lable" of a random set of numbers.
Seed in  a cell insures that set of random numbers remain at that seed.


## 3. Viewing arrays and Integers

In [25]:
# returns all the unique numbers in an array
np.unique(random)

array([1, 3, 4, 5, 6, 7, 9])

 #Size/shape and how to interpret it
    size = (2,3,4,5)
    2 = planes
    3 = rows per place
    4 = placements for array
    5 = elements per array

Array slicing can only go as far as the shape size.

## 4. Manipulating and comparing array

### Arithmetic

In [26]:
a1

array([1, 2, 3])

In [27]:
ones = np.ones(3)

In [28]:
ones

array([1., 1., 1.])

In [29]:
a1 +ones

array([2., 3., 4.])

In [30]:
a1 = np.array([1,2,3])

In [31]:
a1

array([1, 2, 3])

In [32]:
ones

array([1., 1., 1.])

In [33]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [35]:
a1

array([1, 2, 3])

In [36]:
# floor division
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

In [37]:
np.add(a1,ones)

array([2., 3., 4.])

In [38]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [39]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [40]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [41]:
sum(a1)

6

In [42]:
np.sum(a1)

6

### Use python methods on python dtypes, use Numpy methods on numpy

#### Variance = average measure of how different each point is from the mean

In [43]:
import matplotlib as plt


## Reshaping and Transposing

In [44]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [46]:
# Transpose
a2.reshape(2,3)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
# Transpose switches the axises around

## Dot Product

In [49]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))


In [50]:
mat1.shape

(5, 3)

In [51]:
mat2.shape

(5, 3)

In [52]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [53]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [54]:
# Element-wise multiplication
mat2 * mat1

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [55]:
a1.T

array([1, 2, 3])

In [56]:
mat2.dot(mat1.T)

array([[ 51, 130,  67, 115, 111],
       [ 55,  76,  39,  69,  77],
       [ 72, 164,  85, 146, 145],
       [ 20,  33,  27,  37,  56],
       [ 15,  44,  34,  47,  64]])

In [57]:
mat3 = np.dot(mat2, mat1.T)

In [58]:
mat3

array([[ 51, 130,  67, 115, 111],
       [ 55,  76,  39,  69,  77],
       [ 72, 164,  85, 146, 145],
       [ 20,  33,  27,  37,  56],
       [ 15,  44,  34,  47,  64]])

In [59]:
mat3.shape

(5, 5)

Dot product is helpful in finding patterns in arrays of numbers

### Dot Product IRL Example

In [60]:
np.random.seed(7)

sales = np.random.randint(20,size=(5,3))
sales

array([[15,  4,  3],
       [19,  7, 14],
       [ 8, 14, 10],
       [ 8,  7,  6],
       [ 4, 16,  7]])

In [61]:
weekly_sakes = pd.DataFrame(sales,index=["Mon","Tues","Wed","Thu","Fri"])

In [62]:
weekly_sakes

0   1   2
Mon   15   4   3
Tues  19   7  14
Wed    8  14  10
Thu    8   7   6
Fri    4  16   7

In [64]:
weekly_sakes.rename(columns={0:"Cookies",1:"Lemonade",2:"Boobies"})

Cookies  Lemonade  Boobies
Mon        15         4        3
Tues       19         7       14
Wed         8        14       10
Thu         8         7        6
Fri         4        16        7

In [65]:
# Create prices

prices = np.array([10,8,12])

In [67]:
product_prices = pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Cookies","Lemonade","Boobies"])

In [68]:
product_prices

Cookies  Lemonade  Boobies
Price       10         8       12

In [69]:
product_prices.shape

(1, 3)

In [70]:
weekly_sakes.shape

(5, 3)

In [71]:
weekly_sakes.dot(product_prices)

ValueError: matrices are not aligned

In [72]:
weekly_sakes.dot(product_prices.T)

ValueError: matrices are not aligned

In [75]:
weekly_sakes.shape ,product_prices.T.shape

((5, 3), (3, 1))

In [76]:
weekly_sakes.dot(product_prices.T)

ValueError: matrices are not aligned

In [78]:
product_prices(weekly_sakes.T)

TypeError: 'DataFrame' object is not callable

In [79]:
sales

array([[15,  4,  3],
       [19,  7, 14],
       [ 8, 14, 10],
       [ 8,  7,  6],
       [ 4, 16,  7]])

In [80]:
sales.shape

(5, 3)

In [81]:
prices.shape

(3,)

In [82]:
sales.dot(prices)

array([218, 414, 312, 208, 252])

In [83]:
total_sales = sales.dot(prices)

In [84]:
total_sales

array([218, 414, 312, 208, 252])

In [85]:
weekly_sakes["Total Earnings"] = total_sales

In [86]:
weekly_sakes

0   1   2  Total Earnings
Mon   15   4   3             218
Tues  19   7  14             414
Wed    8  14  10             312
Thu    8   7   6             208
Fri    4  16   7             252

### Comparison Operators

In [87]:
a1

array([1, 2, 3])

In [88]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [90]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [91]:
bool_array = a1 <= a2


In [92]:
bool_array

array([[ True,  True,  True],
       [ True,  True,  True]])

In [93]:
a1 > 7

array([False, False, False])

In [94]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

## 5. Sorting Arrays

In [95]:
range_array = np.random.randint(10,size=(3,5))

In [96]:
range_array

array([[0, 7, 6, 3, 5],
       [8, 8, 7, 5, 0],
       [0, 2, 8, 9, 6]])

In [97]:
np.sort(range_array)

array([[0, 3, 5, 6, 7],
       [0, 5, 7, 8, 8],
       [0, 2, 6, 8, 9]])

In [99]:
# Sorts the indexes and what order they would come in order
np.argsort(range_array)

array([[0, 3, 4, 2, 1],
       [4, 3, 2, 0, 1],
       [0, 1, 4, 2, 3]], dtype=int64)

In [101]:
random2

array([[0.65557656, 0.44474551, 0.65958644],
       [0.74017526, 0.04595395, 0.56973258]])

In [102]:
np.argmin(random2)

4

In [103]:
random2.shape

(2, 3)

In [106]:
# We're looking at random 2 on axis 0.
# Comparing vertically
np.argmin(random2,axis=0)

array([0, 1, 1], dtype=int64)

In [107]:
# We're comparing horizontally on axis 1
np.argmin(random2,axis=1)

array([1, 1], dtype=int64)

In [108]:
np.argmin(random2,axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

## 6. Practical Example Numpy

In [112]:
# Turn image into Numpy array
from matplotlib.image import imread

cat = imread("white-cat.jpg")
cat

array([[[ 1,  0,  0],
        [ 1,  0,  0],
        [ 1,  0,  0],
        ...,
        [ 6,  0,  0],
        [ 6,  0,  0],
        [ 6,  0,  0]],

       [[ 1,  0,  0],
        [ 1,  0,  0],
        [ 1,  0,  0],
        ...,
        [ 6,  0,  0],
        [ 6,  0,  0],
        [ 6,  0,  0]],

       [[ 1,  0,  0],
        [ 1,  0,  0],
        [ 1,  0,  0],
        ...,
        [ 6,  0,  0],
        [ 6,  0,  0],
        [ 6,  0,  0]],

       ...,

       [[75, 52, 34],
        [71, 48, 30],
        [71, 48, 32],
        ...,
        [15, 10,  7],
        [12,  7,  4],
        [ 5,  0,  0]],

       [[74, 51, 33],
        [65, 42, 24],
        [70, 47, 29],
        ...,
        [15, 11,  8],
        [13,  9,  6],
        [ 8,  4,  1]],

       [[70, 47, 29],
        [62, 39, 21],
        [72, 49, 31],
        ...,
        [14, 10,  7],
        [12,  8,  5],
        [10,  6,  3]]], dtype=uint8)

In [113]:
cat.size , cat.shape

(1175040, (640, 612, 3))

In [114]:
panda = imread("C:\\Users\\setar\\PycharmProjects\\machine-learning-101\\Images\\panda.png")

In [115]:
panda

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       ...,

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1.

In [116]:
panda.size, panda.shape, panda.ndim

(8770176, (1104, 1986, 4), 3)

In [117]:
panda[:3]

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [118]:
panda[:1]

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [2]:
import numpy as np

In [4]:
a1 = np.array([1,2,3])

In [5]:
a2 = np.array([[1,2,3],[4,5,6]])

In [6]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3 = np.array([[[1,2,3],[3,4,5]],[[2,3,4],[4,5,6]]])

In [8]:
a3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[2, 3, 4],
        [4, 5, 6]]])

In [9]:
a3.ndim

3

In [10]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [11]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [12]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [13]:
import pandas as pd

In [14]:
a1_dataframe = pd.DataFrame(a1)

In [15]:
a1_dataframe

0
0  1
1  2
2  3

In [16]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
np.random.randint(0,10,size=(7,2))

array([[7, 0],
       [5, 7],
       [9, 8],
       [9, 5],
       [4, 5],
       [0, 5],
       [2, 0]])

In [20]:
np.random.random(size=(3,5))

array([[0.13883078, 0.29806113, 0.15369747, 0.57122528, 0.39017364],
       [0.58270516, 0.40872224, 0.83131976, 0.2626085 , 0.20646074],
       [0.63723361, 0.90731941, 0.51395603, 0.55700128, 0.98826794]])

In [24]:
np.random.seed(42)

np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [30]:
np.random.seed(42)
random = np.random.randint(1,10,size=(3,7))
np.unique(random)
random

array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6],
       [5, 2, 8, 6, 2, 5, 1]])

In [31]:
random[0]

array([7, 4, 8, 5, 7, 3, 7])

In [32]:
type(random)

numpy.ndarray

In [33]:
random[:2]

array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6]])

In [35]:
random[:2,:2]

array([[7, 4],
       [8, 5]])

In [37]:
np.random.seed(33)

a1 = np.random.randint(0,10,size=(3,5))
a2 = np.ones(shape=(3,5))
a1


array([[4, 7, 8, 2, 2],
       [9, 9, 3, 6, 3],
       [3, 1, 7, 6, 0]])

In [38]:
a2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
a1.shape, a2.shape

((3, 5), (3, 5))

In [40]:
np.add(a1,a2)

array([[ 5.,  8.,  9.,  3.,  3.],
       [10., 10.,  4.,  7.,  4.],
       [ 4.,  2.,  8.,  7.,  1.]])

In [42]:
a3 = np.ones(shape=(5,3))

In [43]:
a3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.add(a3,a1)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [45]:
a4 = np.ones(shape=(3,5))

In [46]:
np.subtract(a4,a3)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [47]:
np.subtract(a2,a4)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])