In [1]:
import numpy as np

## DataTypes and attributes

In [2]:
# main datatype = ndarray (n- dimentional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a1.shape

(3,)

In [6]:
a1.ndim, a2.ndim

(1, 2)

In [7]:
a1.dtype

dtype('int32')

In [8]:
a1.size, a2.size

(3, 6)

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(a1)

In [11]:
df

0
0  1
1  2
2  3

In [12]:
df2 = pd.DataFrame(a2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

## 2. Creating Arrays

In [13]:
ones = np.ones((2,3))

In [14]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
zeros = np.zeros((2,3))
zeros.dtype

dtype('float64')

In [16]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array = np.arange(0,10,4)

In [18]:
range_array

array([0, 4, 8])

In [19]:
random = np.random.randint(0,10,size=(2,4))

In [20]:
random

array([[4, 1, 6, 8],
       [6, 1, 4, 5]])

In [21]:
random2 = np.random.random((2,3))
random2

array([[0.45214388, 0.43729615, 0.91576428],
       [0.62524086, 0.63089948, 0.56539873]])

In [22]:
random3 = np.random.rand(4,3)
random3

array([[0.4541936 , 0.74893588, 0.03717684],
       [0.67511798, 0.17053931, 0.95785661],
       [0.52950216, 0.3123085 , 0.91178577],
       [0.99874084, 0.40795415, 0.79835731]])

In [25]:
# Pseudo-random numbers
# np.random.seed()


Seed:
Seed is the "lable" of a random set of numbers.
Seed in  a cell insures that set of random numbers remain at that seed.


## 3. Viewing arrays and Integers

In [27]:
# returns all the unique numbers in an array
np.unique(random)

array([1, 4, 5, 6, 8])

 #Size/shape and how to interpret it
    size = (2,3,4,5)
    2 = planes
    3 = rows per place
    4 = placements for array
    5 = elements per array

Array slicing can only go as far as the shape size.

## 4. Manipulating and comparing array

### Arithmetic

In [29]:
a1

array([1, 2, 3])

In [30]:
ones = np.ones(3)

In [31]:
ones

array([1., 1., 1.])

In [37]:
a1 +ones

array([2., 2., 2.])

In [38]:
a1 = np.array([1,2,3])

In [39]:
a1

array([1, 2, 3])

In [40]:
ones

array([1., 1., 1.])

In [41]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [43]:
a1

array([1, 2, 3])

In [46]:
# floor division
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

In [47]:
np.add(a1,ones)

array([2., 3., 4.])

In [48]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [49]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [50]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [51]:
sum(a1)

6

In [52]:
np.sum(a1)

6

### Use python methods on python dtypes, use Numpy methods on numpy

#### Variance = average measure of how different each point is from the mean